---
title: "Week 3: Agents and Tools"
format:
  revealjs:
    slide-number: true
    incremental: true
    center-title-slide: true
    theme: [default, ../../theme/digipen.scss]
    highlight-style: github
    width: 1050
    height: 700
    margin: 0.15
    mermaid:
      theme: neutral
logo: ../../theme/logos/DigiPen_RGB_Red.png
bibliography: references.bib
---

## Recap of Last Week's Lecture

- Understood the evolution and licensing of models from GPT-2 through to modern day
- Understood instruction-tuned models, how they work, and how to configure
- Setup and used OpenRouter for accessing hosted models
- Understood the OpenAI API specification, the request/response payload, parameters, streaming, and structured output
- Created and shared a chatbot using a Gradio-based UI

## Lesson Objectives

- Describe the fundamental concepts behind Agents/Agentic AI
- Explore and provide feedback on an existing multi-agent setup
- Understand available agent SDKs, how they differ, and advantages/disadvantages
- Use the OpenAI Agents SDK to build an multi-agent system from scratch, including document indexing and retrieval
- Understand and implement tool calls and implement using OpenAI’s function calling and via MCP

# Looking Ahead to Next Week

## Looking Ahead to Next Week

- [This week's assignment!](https://simonguest.github.io/CS-394/src/03/assignment.html){.external target="_blank"}
- TBD

# References

## References
